import { describe, expect, it } from 'vitest';
import {
  aiHeuristicProvenance,
  getAIProvenanceSourceStatus,
  normalizeAIProvenance,
} from './aiProvenance';

describe('aiProvenance', () => {
  it('defaults AI output to explicit heuristic provenance', () => {
    expect(normalizeAIProvenance()).toMatchObject({
      provenanceMode: 'heuristic',
      sourceLabel: aiHeuristicProvenance.sourceLabel,
      providerBacked: false,
      isFallback: false,
    });
    expect(getAIProvenanceSourceStatus('heuristic')).toBe('heuristic');
  });

  it('preserves provider-backed provenance supplied by a future AI endpoint', () => {
    expect(normalizeAIProvenance({
      provenanceMode: 'live_model',
      sourceLabel: 'OpenAI GPT model',
      sourceDetail: 'Generated by provider-backed model routing.',
      providerBacked: true,
    })).toMatchObject({
      provenanceMode: 'live_model',
      sourceLabel: 'OpenAI GPT model',
      sourceDetail: 'Generated by provider-backed model routing.',
      providerBacked: true,
      isFallback: false,
    });
    expect(getAIProvenanceSourceStatus('live_model')).toBe('provider');
  });
});
