import React from 'react';
import { Badge } from './Badge';

export type SourceStatusKind =
  | 'account'
  | 'demo'
  | 'fallback'
  | 'heuristic'
  | 'live'
  | 'local'
  | 'provider'
  | 'unavailable';

type BadgeVariant = React.ComponentPropsWithoutRef<typeof Badge>['variant'];

const sourceStatusCopy: Record<SourceStatusKind, {
  label: string;
  description: string;
  variant: BadgeVariant;
  dotClassName: string;
}> = {
  account: {
    label: 'Saved to account',
    description: 'This data is stored with the signed-in account when sync succeeds.',
    variant: 'success',
    dotClassName: 'bg-success',
  },
  demo: {
    label: 'Demo mode',
    description: 'This workflow is visible for review, but provider-backed production state is not active.',
    variant: 'warning',
    dotClassName: 'bg-warning',
  },
  fallback: {
    label: 'Fallback data',
    description: 'Primary data is unavailable, so this view is using fallback information.',
    variant: 'warning',
    dotClassName: 'bg-warning',
  },
  heuristic: {
    label: 'Heuristic source',
    description: 'This output is generated by rules or heuristics instead of a provider-backed live model.',
    variant: 'default',
    dotClassName: 'bg-accent',
  },
  live: {
    label: 'Live source',
    description: 'This view is using the live account data source.',
    variant: 'success',
    dotClassName: 'bg-success',
  },
  local: {
    label: 'Saved locally',
    description: 'This data is stored in this browser and may not sync across devices.',
    variant: 'warning',
    dotClassName: 'bg-warning',
  },
  provider: {
    label: 'Provider backed',
    description: 'This action is backed by an external provider handoff.',
    variant: 'success',
    dotClassName: 'bg-success',
  },
  unavailable: {
    label: 'Unavailable',
    description: 'This capability is intentionally unavailable in the current build.',
    variant: 'outline',
    dotClassName: 'bg-[var(--text-muted)]',
  },
};

interface SourceStatusBadgeProps extends Omit<React.ComponentPropsWithoutRef<typeof Badge>, 'description' | 'variant'> {
  status: SourceStatusKind;
  label?: string;
  description?: React.ReactNode;
  variant?: BadgeVariant;
}

export const getSourceStatusDefaults = (status: SourceStatusKind) => sourceStatusCopy[status];

export const SourceStatusBadge = React.forwardRef<HTMLSpanElement, SourceStatusBadgeProps>(
  ({ status, label, description, variant, children, className, ...props }, ref) => {
    const defaults = sourceStatusCopy[status];
    const visibleLabel = children || label || defaults.label;

    return (
      <Badge
        ref={ref}
        variant={variant || defaults.variant}
        description={description || defaults.description}
        className={className}
        data-ui="source-status-badge"
        data-source-status={status}
        {...props}
      >
        <span className={`mr-1.5 h-1.5 w-1.5 shrink-0 rounded-full ${defaults.dotClassName}`} aria-hidden="true" />
        <span className="min-w-0 truncate">{visibleLabel}</span>
      </Badge>
    );
  }
);

SourceStatusBadge.displayName = 'SourceStatusBadge';
