export type AIProvenanceMode = 'live_model' | 'heuristic' | 'fallback' | 'unavailable';

export interface AIProvenance {
  provenanceMode: AIProvenanceMode;
  sourceLabel: string;
  sourceDetail: string;
  controlNote: string;
  providerBacked: boolean;
  isFallback: boolean;
}

export type AIProvenanceInput = Partial<Omit<AIProvenance, 'provenanceMode'>> & {
  provenanceMode?: AIProvenanceMode | string;
};

export type AIProvenanceSourceStatus = 'provider' | 'heuristic' | 'fallback' | 'unavailable';

const compact = (value?: unknown) => (
  typeof value === 'string' ? value.replace(/\s+/g, ' ').trim() : ''
);

const commonControlNote = 'This is guidance only. It does not change your profile, resume, applications, learning progress, or settings.';

export const aiHeuristicProvenance: AIProvenance = {
  provenanceMode: 'heuristic',
  sourceLabel: 'Heuristic AI guidance',
  sourceDetail: 'Generated by the backend AI API in heuristic mode for this build. Review before applying it in another workflow.',
  controlNote: commonControlNote,
  providerBacked: false,
  isFallback: false,
};

export const aiLiveModelProvenance: AIProvenance = {
  provenanceMode: 'live_model',
  sourceLabel: 'Live AI model',
  sourceDetail: 'Generated by a configured AI model provider. Review before applying it in another workflow.',
  controlNote: commonControlNote,
  providerBacked: true,
  isFallback: false,
};

export const aiFallbackProvenance: AIProvenance = {
  provenanceMode: 'fallback',
  sourceLabel: 'Fallback AI guidance',
  sourceDetail: 'Generated from fallback logic because the primary AI provider or backend source was unavailable.',
  controlNote: commonControlNote,
  providerBacked: false,
  isFallback: true,
};

export const aiUnavailableProvenance: AIProvenance = {
  provenanceMode: 'unavailable',
  sourceLabel: 'AI service unavailable',
  sourceDetail: 'No AI model response was produced. This is a safe failure message and no workflow data changed.',
  controlNote: commonControlNote,
  providerBacked: false,
  isFallback: true,
};

const provenanceDefaults: Record<AIProvenanceMode, AIProvenance> = {
  live_model: aiLiveModelProvenance,
  heuristic: aiHeuristicProvenance,
  fallback: aiFallbackProvenance,
  unavailable: aiUnavailableProvenance,
};

const normalizeMode = (value?: string): AIProvenanceMode | null => {
  if (value === 'live_model' || value === 'heuristic' || value === 'fallback' || value === 'unavailable') {
    return value;
  }
  return null;
};

export const normalizeAIProvenance = (input?: AIProvenanceInput | null): AIProvenance => {
  const explicitMode = normalizeMode(compact(input?.provenanceMode));
  const inferredMode = explicitMode
    || (input?.providerBacked ? 'live_model' : null)
    || (input?.isFallback ? 'fallback' : null)
    || 'heuristic';
  const defaults = provenanceDefaults[inferredMode];

  return {
    provenanceMode: inferredMode,
    sourceLabel: compact(input?.sourceLabel) || defaults.sourceLabel,
    sourceDetail: compact(input?.sourceDetail) || defaults.sourceDetail,
    controlNote: compact(input?.controlNote) || defaults.controlNote,
    providerBacked: input?.providerBacked ?? defaults.providerBacked,
    isFallback: input?.isFallback ?? defaults.isFallback,
  };
};

export const getAIProvenanceSourceStatus = (mode: AIProvenanceMode): AIProvenanceSourceStatus => {
  if (mode === 'live_model') return 'provider';
  if (mode === 'unavailable') return 'unavailable';
  if (mode === 'fallback') return 'fallback';
  return 'heuristic';
};
