apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - infrastructure.yaml
  - services/api-gateway.yaml
  - services/auth-service.yaml
  - services/user-service.yaml
  - services/profile-service.yaml
  - services/job-service.yaml
  - services/lms-service.yaml
  - services/application-service.yaml
  - services/challenge-service.yaml
  - services/company-service.yaml
  - services/notification-service.yaml
  - services/search-service.yaml
  - services/gamification-service.yaml
  - services/messaging-service.yaml
  - services/networking-service.yaml
  - services/ai-service.yaml
  - services/chat-service.yaml
  - services/payment-service.yaml
  - services/file-service.yaml
  - notification-digest-cronjobs.yaml
