spring:
  application:
    name: file-service

server:
  port: 8100

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
