spring:
  application:
    name: payment-service
  datasource:
    url: jdbc:postgresql://ts-postgres:5432/payment_db
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

server:
  port: 8098

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
