server:
  port: 8097

spring:
  application:
    name: chat-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/chatservice
      database: chatservice
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
